### ISSUE TITLE
Can I have multiple editor instances?

### ISSUE THREAD

**Issue by adn0n** [10play/10tap-editor#133]
So, right now, I'm trying to have multiple notes. I'm also trying to set the initialContent to the saved content in the database. But the editor only seems to be working in one note.
It does work if I pass in a custom DEV_SERVER_URL with that note id, but I'm afraid this is going to cause some memory and scalability issues. Is there a better way of doing this?

**Comment by mandrade2** [comment]
I do have it working when showing multiple editor instances. I am using the advanced setup so I do have some extra Tiptap plugins installed.

On 12-06-2024, at 14:23, Adnan ***@***.***> wrote:

﻿

So, right now, I'm trying to have multiple notes. I'm also trying to set the initialContent to the saved content in the database. But the editor only seems to be working in one note.
It does work if I pass in a custom DEV_SERVER_URL with that note id, but I'm afraid this is going to cause some memory and scalability issues. Is there a better way of doing this?

**Comment by 17Amir17** [comment]
Hey, TenTap should work with many editor instances, you do need a new editor instance for each editor (useEditor)
`DEV_SERVER_URL` should only be used when developing with the advanced setup.

If no content is being displayed something must have failed inside the web-view could you should us the error? This is how you can inspect web-view logs:
https://github.com/react-native-webview/react-native-webview/blob/master/docs/Debugging.md#debugging-webview-contents

**Comment by adn0n** [comment]
<img width="582" alt="image" src="https://github.com/10play/10tap-editor/assets/76644985/683ec767-0cea-4333-8580-a46603007f6d">
This is the error I get

**Comment by 17Amir17** [comment]
> <img width="582" alt="image" src="https://github.com/10play/10tap-editor/assets/76644985/683ec767-0cea-4333-8580-a46603007f6d">
> 
> This is the error I get

This error should be fixed on the latest version. What version are you on, could you try updating?

**Comment by 17Amir17** [comment]
Closing for now, lmk if it persists

**Comment by adn0n** [comment]
Still the same problem, experiencing it quite frequently. I'm using the latest version.
Here's the package.json file
`{
  "name": "editor-test",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "lint": "eslint .",
    "start": "react-native start",
    "test": "jest"
  },
  "dependencies": {
    "@10play/tentap-editor": "^0.5.3",
    "@expo/vector-icons": "^14.0.2",
    "@react-native-async-storage/async-storage": "^1.23.1",
    "@react-native-voice/voice": "^3.2.4",
    "@react-navigation/bottom-tabs": "^6.5.20",
    "@react-navigation/native": "^6.1.17",
    "@react-navigation/stack": "^6.3.29",
    "@types/react-native-vector-icons": "^6.4.18",
    "axios": "^1.7.2",
    "lodash": "^4.17.21",
    "moment": "^2.30.1",
    "react": "^18.2.0",
    "react-native": "0.74.1",
    "react-native-gesture-handler": "^2.16.2",
    "react-native-modal": "^13.0.1",
    "react-native-reanimated": "^3.12.0",
    "react-native-safe-area-context": "^4.10.4",
    "react-native-screens": "^3.31.1",
    "react-native-swipe-list": "^0.0.2",
    "react-native-vector-icons": "^10.1.0",
    "react-native-webview": "^13.10.2"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@babel/preset-env": "^7.20.0",
    "@babel/runtime": "^7.20.0",
    "@react-native/babel-preset": "0.74.83",
    "@react-native/eslint-config": "0.74.83",
    "@react-native/metro-config": "0.74.83",
    "@react-native/typescript-config": "0.74.83",
    "@types/react": "^18.2.6",
    "@types/react-test-renderer": "^18.0.0",
    "babel-jest": "^29.6.3",
    "eslint": "^8.19.0",
    "jest": "^29.6.3",
    "prettier": "2.8.8",
    "react-test-renderer": "18.2.0",
    "tailwindcss": "^3.3.2",
    "typescript": "5.0.4"
  },
  "engines": {
    "node": ">=18"
  }
}`

**Comment by 17Amir17** [comment]
Could you provide a minimal reproducible example?

**Comment by GuySerfaty** [comment]
We can see this on very old android devices @adn0n can you verify iOS is working for you?

I see:
```
Scheme is missing its top node type ('doc')
```

Might be related to 
https://github.com/react-native-webview/react-native-webview/issues/1609

**Comment by jbernhardt-x-team** [comment]
> <img alt="image" width="582" src="https://private-user-images.githubusercontent.com/76644985/339586629-683ec767-0cea-4333-8580-a46603007f6d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0MDg4MDUsIm5iZiI6MTcyMDQwODUwNSwicGF0aCI6Ii83NjY0NDk4NS8zMzk1ODY2MjktNjgzZWM3NjctMGNlYS00MzMzLTg1ODAtYTQ2NjAzMDA3ZjZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA4VDAzMTUwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTllMDgyYzkzNzg0ODRjMzBmNmVhZjAyMzQ3ZGFiZjEzODA4ODhlMzgwNTc3NDgwYTI1YTczZDE1MGVkMDdmZTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UEytUfhwRshem3SFG8Idp4NNn5nmtI-J8RULNW5yoMI"> This is the error I get

I'm getting this exact error. I have a `FlatList` that renders a component that eventually renders a `RichText` component. I don't have multiple `RichText` in a single component but I noticed that only on Android some of the `RichText` rendered in the list throw this error. I have the very basic implementation of the `RichText` from [here](https://10play.github.io/10tap-editor/docs/intro#usage)

I'm testing on a Pixel 8 Pro running latest Android version.

**Comment by 17Amir17** [comment]
I've found a way to reproduce this consistently.
It happens on some androids - I am using Pixel 5 API 32 Android 12L Emulator, and it only happens when reopening the app, and mounting the editor for the first time, will work on a fix

**Comment by jbernhardt-x-team** [comment]
> I've found a way to reproduce this consistently. It happens on some androids - I am using Pixel 5 API 32 Android 12L Emulator, and it only happens when reopening the app, and mounting the editor for the first time, will work on a fix

In case it can by any helpful, I found [this](https://github.com/react-native-webview/react-native-webview/issues/3377) thread where an alternative prop is being exposed, I'm going to patch locally and see if I have better results

**Comment by 17Amir17** [comment]
Should be fixed on `0.5.11` - let us know if this solves the case for you - if you are using the advanced setup you will need to update you `index.ts` https://10play.github.io/10tap-editor/docs/setup/advancedSetup#step-4---add-indexhtml-advancededitortsx-and-indextsx

**Comment by adn0n** [comment]
Working fine now, thank you!
