### ISSUE TITLE
[PRO]: Dynamic Height weird behavior in Android V2

### ISSUE THREAD

**Issue by aatar-hu** [10play/10tap-editor#244]
**Describe the bug**
Some days ago I created [this](https://github.com/10play/10tap-editor/issues/236) issue.
I updated to the last version of the lib but still there is a weird behavior in Android when pressing `Enter`. Now the text moves up and then moves back down in less than 1 second. Can you fix that to avoid the text movements?

Also, I'm implementing Mentions with this lib and on Nov 24 Guy sent me via email a full example of mentions with dynamic height. Could you please send me the example again with this issue fixed? My email is ariel.atar@humand.co

**To Reproduce**
1. Write some text in the editor
2. Press `Enter`
3. The text moves up and then moves back down in less than 1 second

**Expected behavior**
The text shouldn't move up or down when I press `Enter`

**Screenshots**

https://github.com/user-attachments/assets/9bbabe15-2288-42c7-90c4-44b0dd86110b

**Comment by 17Amir17** [comment]
We're unable to reproduce this with the code you have provided, mind sharing your device and Android version?

https://github.com/user-attachments/assets/042edbbf-247c-499d-9875-929dfdc7c5c5

**Comment by aatar-hu** [comment]
Of course! This is my device
<img width="203" alt="Screenshot 2024-12-16 at 14 48 08" src="https://github.com/user-attachments/assets/7d9856fc-c20d-416a-953b-acaed15882ad" />

**Comment by AliRehman7141** [comment]
I'm also facing this issue on ios Simulator using `"@10play/tentap-editor": "^0.5.24"`
Video attached here
https://github.com/10play/10tap-editor/issues/236#issuecomment-2560976119

**Comment by 17Amir17** [comment]
@aatar-hu should be fixed on [0.5.31](https://github.com/10play/10tap-editor/releases/tag/v0.5.31)
LMK if this solves your issue

**Comment by aatar-hu** [comment]
Hi @17Amir17! I updated to the last version 0.5.33 but the bug persists 😢

**Comment by 17Amir17** [comment]
@aatar-hu could you share a repo that reproduces this? I am not able to reproduce this anymore

**Comment by aatar-hu** [comment]
Hi @17Amir17 ! I tested again, now in version 0.6.0 and it's working ok! Thanks! 👍
